version: "3"

services:
  ics-display:
    build: .
    environment:
      - number_of_events=25
      - days_back=0
      - days_forward=14
      - skip_string=SKIP_ME
      - highlight_today=false
      - highlight_calendar1=djoit
      - highlight_calendar2=
      - highlight_calendar3=
      - highlight_calendar4=
      - highlight_calendar5=
      - highlight_calendar6=
      - highlight_calendar7=
      - highlight_calendar8=
      - highlight_calendar9=
      - highlight_keyword="#PRI"
      - darken_past=true
      - darken_calendars=false
      - darken_keyword="#DARK"
      - show_ical_errors=true
      - cal1_name=oconnell
      - cal1_url=https://calendar.google.com/calendar/ical/bishopoconnell.org_p8d7f7mf6p0giefbdnmvpljs5s%40group.calendar.google.com/private-3519fc2c580dd7f1e7d4deaeb4e5890e/basic.ics
      - cal2_name=djoit
      - cal2_url=https://calendar.google.com/calendar/ical/bishopoconnell.org_7hoppl37v1ah40j65gop7dt98o%40group.calendar.google.com/private-b2d4a519648d4ea86d1f65964d9b9d75/basic.ics
      - cal3_name=
      - cal3_url=
      - cal4_name=
      - cal4_url=
      - cal5_name=
      - cal5_url=
      - cal6_name=
      - cal6_url=
      - cal7_name=
      - cal7_url=
      - cal8_name=
      - cal8_url=
      - cal9_name=
      - cal9_url=
    ports:
      - "5000:80"
    volumes:
      - ./bg.jpg:/var/www/html/bg.jpg
